apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: spring-vault-direct-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APP_NAME}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}
  spec:
    triggers:
      -
        type: ConfigChange
      -
        type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${APP_NAME}
          from:
            kind: ImageStreamTag
            name: ${IMAGE_NAME}:latest
    replicas: 1
    template:
      metadata:
        labels:
          app: ${APP_NAME}
      spec:
        containers:
          - name: ${APP_NAME}
            image: ${IMAGE_NAME}:latest
            imagePullPolicy: Always
            env:
            - name: "VAULT_HOST"
              value: ${VAULT_HOST}
            - name: "VAULT_PORT"
              value: ${VAULT_PORT}
            livenessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 60
              periodSeconds: 3
            readinessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 60
              periodSeconds: 3

parameters:
- description: Application Name
  name: APP_NAME
  required: true
  value: "test1"
- description: Image Name
  name: IMAGE_NAME
  required: true
  value: "spring-vault-direct"
- description: Vault Host
  name: VAULT_HOST
  required: true
  value: "vault-vault-controller.apps.ocp.datr.eu"
- description: Vault Port
  name: VAULT_PORT
  required: true
  value: "443"