apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-native-example
  name: spring-native-example 
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-native-example
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: spring-native-example
spec:
  triggers:
    -
      type: ConfigChange
    -
      type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - spring-native-example
        from:
          kind: ImageStreamTag
          namespace: spring-native-example
          name: 'spring-native-example:latest'
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-native-example       
    spec:
      containers:
        - name: spring-native-example
          image: "spring-native-example/spring-native-example:latest"
          imagePullPolicy: Always
          env:
          - name: "VAULT_HOST"
            value: "vault-vault-controller.apps.ocp.datr.eu"
          - name: "VAULT_PORT"
            value: "443"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3 
          volumeMounts:
          - name: keystore-volume
            mountPath: /var/run/secrets/java.io/keystores            
      volumes:
      - name: keystore-volume
        emptyDir: {}                                                              
