apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: BuildConfig-template
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${BASE_IMAGE}
          namespace: ${BASE_IMAGE_NAMESPACE}
      type: Source

parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: basket
- description: Base Docker image namespace.
  name: BASE_IMAGE_NAMESPACE
  required: true
  value: "openshift"
- description: Base Docker image.
  name: BASE_IMAGE
  required: true
  value: "redhat-openjdk18-openshift:latest"